skip-check:
  - DL3018 # Pin versions in apk add
  - CKV_GHA_7 # The build output cannot be affected by user parameters other than the build entry point and the top-level source location.
  - CKV2_GHA_1 # Ensure top-level permissions are not set to write-all
